"""
obsidian.py — Update the Obsidian sermon transcript index.

Appends or updates a row in:
    <vault>/JRP/Videos/transcript-index.md

Row format:
    | C0072 | 2026-05-15 | PASS_WITH_AUDIO_CHECK | 3 names pending |

If the vault is not found, logs a warning and skips silently.
If the index file does not yet exist it is created with a header row.
"""

from __future__ import annotations

import logging
import re
from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .discovery import SermonFolder
    from .gate import GateResult

logger = logging.getLogger(__name__)

# Relative path inside the Obsidian vault
_INDEX_RELATIVE = Path("JRP") / "Videos" / "transcript-index.md"

_TABLE_HEADER = (
    "| Sermon | Date | Gate Status | Notes |\n"
    "|--------|------|-------------|-------|\n"
)

_ROW_RE = re.compile(
    r"^\|\s*(?P<code>C\d{3,4})\s*\|",
    re.IGNORECASE,
)


def _build_notes(gate: "GateResult") -> str:
    """Produce a short notes string for the index row."""
    queue_len = len(gate.audio_review_queue)
    if gate.status.value == "BLOCKED":
        reasons_short = "; ".join(gate.reasons[:1])
        return f"BLOCKED: {reasons_short[:60]}"
    if queue_len:
        return f"{queue_len} name{'s' if queue_len > 1 else ''} pending"
    if gate.warnings:
        return gate.warnings[0][:60]
    return "OK"


def _build_row(sermon: "SermonFolder", gate: "GateResult") -> str:
    today = date.today().isoformat()
    notes = _build_notes(gate)
    status = gate.status.value
    return f"| {sermon.code} | {today} | {status} | {notes} |\n"


def update_index(
    sermon: "SermonFolder",
    gate: "GateResult",
    obsidian_vault: Path | None,
) -> None:
    """
    Append or update the row for *sermon* in the Obsidian transcript index.

    Parameters
    ----------
    sermon:
        The processed SermonFolder.
    gate:
        The GateResult produced for this sermon.
    obsidian_vault:
        Path to the root of the Obsidian vault.  Pass None to skip silently.
    """
    if obsidian_vault is None:
        logger.debug("No Obsidian vault path supplied; skipping index update.")
        return

    vault = Path(obsidian_vault)
    if not vault.exists() or not vault.is_dir():
        logger.warning(
            "Obsidian vault not found at %s — skipping transcript index update.", vault
        )
        return

    index_path = vault / _INDEX_RELATIVE
    new_row = _build_row(sermon, gate)

    # ------------------------------------------------------------------
    # Read existing file (or start fresh)
    # ------------------------------------------------------------------
    if index_path.exists():
        existing = index_path.read_text(encoding="utf-8")
    else:
        # Create parent dirs and start with a header
        index_path.parent.mkdir(parents=True, exist_ok=True)
        existing = (
            "# Transcript Index\n\n"
            "Auto-generated by ESTRS. Do not edit the table rows manually.\n\n"
            + _TABLE_HEADER
        )

    # ------------------------------------------------------------------
    # Update or append the row for this sermon code
    # ------------------------------------------------------------------
    lines = existing.splitlines(keepends=True)
    updated = False
    new_lines: list[str] = []

    for line in lines:
        m = _ROW_RE.match(line)
        if m and m.group("code").upper() == sermon.code.upper():
            new_lines.append(new_row)
            updated = True
        else:
            new_lines.append(line)

    if not updated:
        # Ensure there's a trailing newline before appending
        if new_lines and not new_lines[-1].endswith("\n"):
            new_lines.append("\n")
        new_lines.append(new_row)

    index_path.write_text("".join(new_lines), encoding="utf-8")
    action = "updated" if updated else "appended"
    logger.info(
        "Obsidian index %s: row for %s → %s",
        action,
        sermon.code,
        gate.status.value,
    )
