"""ESTRS — Markdown report generator.

Writes all output files into the sermon folder.  Never overwrites source
transcripts.  All output filenames are listed in config.py.
"""
from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path

from .comparison import ComparisonResult
from .config import (
    OUT_AUDIO_QUEUE,
    OUT_COMPARISON,
    OUT_GATE,
    OUT_LOG,
    OUT_NAMES,
    OUT_SCRIPTURE,
    VERSION,
)
from .gate import GateDecision, GateStatus
from .names import NameCandidate
from .scripture import ScriptureAudit
from .terminology import TerminologyAudit


def _ts() -> str:
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S')


def _safe_write(path: Path, content: str) -> None:
    """Write *content* to *path*.  Never raises; logs errors to stderr."""
    try:
        path.write_text(content, encoding='utf-8')
    except OSError as exc:
        import sys
        print(f"[ESTRS] WARNING: cannot write {path}: {exc}", file=sys.stderr)


# ── transcript_comparison.md ──────────────────────────────────────────────────

def write_comparison(folder: Path, result: ComparisonResult) -> None:
    lines: list[str] = [
        f"# Transcript Comparison",
        f"",
        f"*Generated by ESTRS v{VERSION} — {_ts()}*",
        f"",
        f"## Summary",
        f"",
        *result.summary_lines,
        f"",
        f"**Confidence level:** {result.status}",
        f"",
    ]

    if result.assemblyai_path:
        lines.append(f"- **AssemblyAI source:** `{result.assemblyai_path.name}`")
    if result.macwhisper_path:
        lines.append(f"- **MacWhisper source:** `{result.macwhisper_path.name}`")
    lines.append("")

    # Diff blocks — only emit the differing ones (≤ 50 blocks to keep it readable)
    diff_blocks = [b for b in result.line_diff_blocks if b.tag != 'equal']
    if diff_blocks:
        lines += [
            f"## Differences ({len(diff_blocks)} block(s))",
            "",
        ]
        for i, blk in enumerate(diff_blocks[:50], start=1):
            lines.append(f"### Block {i} — `{blk.tag}`")
            lines.append("")
            if blk.a_lines:
                lines.append("**AssemblyAI:**")
                lines.append("```")
                lines.extend(blk.a_lines[:8])
                if len(blk.a_lines) > 8:
                    lines.append(f"… ({len(blk.a_lines) - 8} more lines)")
                lines.append("```")
            if blk.b_lines:
                lines.append("**MacWhisper:**")
                lines.append("```")
                lines.extend(blk.b_lines[:8])
                if len(blk.b_lines) > 8:
                    lines.append(f"… ({len(blk.b_lines) - 8} more lines)")
                lines.append("```")
            lines.append("")
        if len(diff_blocks) > 50:
            lines.append(f"*… {len(diff_blocks) - 50} additional blocks not shown.*")
    else:
        lines.append("## Differences\n\n*No differing blocks detected.*\n")

    _safe_write(folder / OUT_COMPARISON, '\n'.join(lines))


# ── name_resolution.md ────────────────────────────────────────────────────────

def write_names(folder: Path, candidates: list[NameCandidate]) -> None:
    lines: list[str] = [
        f"# Name Resolution",
        f"",
        f"*Generated by ESTRS v{VERSION} — {_ts()}*",
        f"",
    ]

    if not candidates:
        lines.append("*No uncertain names detected.*\n")
        _safe_write(folder / OUT_NAMES, '\n'.join(lines))
        return

    lines += [
        f"**Total uncertain names:** {len(candidates)}",
        f"",
        f"| Name | Confidence | Sources | Occurrences |",
        f"|------|-----------|---------|-------------|",
    ]
    for c in candidates:
        sources_str = ', '.join(c.sources)
        lines.append(
            f"| {c.text} | {c.confidence} | {sources_str} | {len(c.locations)} |"
        )
    lines.append("")
    lines.append("## Detail")
    lines.append("")

    for c in candidates:
        lines.append(f"### {c.text}")
        lines.append(f"")
        lines.append(f"- **Confidence:** {c.confidence}")
        lines.append(f"- **Sources:** {', '.join(c.sources)}")
        lines.append(f"- **Occurrences:** {len(c.locations)}")
        if c.note:
            lines.append(f"- **Note:** {c.note}")
        lines.append("")
        lines.append("**Context samples:**")
        lines.append("")
        for ctx in c.contexts[:3]:
            lines.append(f"> {ctx}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Action: verify uncertain names against the audio and update this file.*")
    lines.append("")

    _safe_write(folder / OUT_NAMES, '\n'.join(lines))


# ── scripture_audit.md ────────────────────────────────────────────────────────

def write_scripture(folder: Path, audit: ScriptureAudit,
                    terminology_audit: TerminologyAudit | None = None) -> None:
    lines: list[str] = [
        f"# Scripture Audit",
        f"",
        f"*Generated by ESTRS v{VERSION} — {_ts()}*",
        f"",
        f"**Total references found:** {audit.total_count}",
        f"**Books cited:** {len(audit.books_cited)}",
        f"",
    ]

    if audit.books_cited:
        lines.append("## Books Cited")
        lines.append("")
        for book in audit.books_cited:
            lines.append(f"- {book}")
        lines.append("")

    if audit.refs:
        lines += [
            "## All References",
            "",
            "| Book | Chapter | Verse | Source | Line |",
            "|------|---------|-------|--------|------|",
        ]
        for r in audit.refs:
            verse = str(r.verse_start) if r.verse_start else '—'
            if r.verse_end:
                verse += f"–{r.verse_end}"
            lines.append(
                f"| {r.canonical_book} | {r.chapter} | {verse} | {r.source} | {r.line_no} |"
            )
        lines.append("")

    if audit.format_warnings:
        lines.append("## Format Warnings")
        lines.append("")
        for w in audit.format_warnings:
            lines.append(f"- ⚠️  {w}")
        lines.append("")

    # Embed terminology audit here too
    if terminology_audit:
        lines += [
            "## Terminology Audit",
            "",
        ]
        if terminology_audit.term_hits:
            lines += [
                f"**{terminology_audit.total_terms_found} known term(s) identified:**",
                "",
                "| Term | Category | Note |",
                "|------|----------|------|",
            ]
            for h in terminology_audit.term_hits:
                lines.append(f"| {h.term} | {h.category} | {h.note} |")
            lines.append("")
        else:
            lines.append("*No special terminology detected.*\n")

        if terminology_audit.error_hits:
            lines += [
                "### Likely Transcription Errors",
                "",
            ]
            for e in terminology_audit.error_hits:
                lines.append(f"- **Found:** `{e.pattern_found}` → **Suggested:** `{e.suggested_correction}` ({e.reason})")
            lines.append("")

    _safe_write(folder / OUT_SCRIPTURE, '\n'.join(lines))


# ── publication_gate.md ───────────────────────────────────────────────────────

def write_gate(folder: Path, decision: GateDecision,
               sermon_id: str = '') -> None:
    icon = {'PASS': '✅', 'PASS_WITH_AUDIO_CHECK': '⚠️', 'BLOCKED': '🚫'}
    status_icon = icon.get(decision.status.value, '?')

    lines: list[str] = [
        f"# Publication Gate",
        f"",
        f"*Generated by ESTRS v{VERSION} — {_ts()}*",
        f"",
        f"## Status: {status_icon} {decision.status.value}",
        f"",
    ]

    if sermon_id:
        lines.insert(2, f"**Sermon:** `{sermon_id}`\n")

    if decision.reasons:
        lines.append("## Reasons")
        lines.append("")
        for r in decision.reasons:
            lines.append(f"- {r}")
        lines.append("")

    if decision.audio_check_items:
        lines.append("## Audio Check Required")
        lines.append("")
        for item in decision.audio_check_items:
            lines.append(f"- {item}")
        lines.append("")

    if decision.recommendations:
        lines.append("## Recommendations")
        lines.append("")
        for rec in decision.recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    lines += [
        "---",
        "",
        "| Gate rule | Result |",
        "|-----------|--------|",
        f"| Status | **{decision.status.value}** |",
        f"| Audio items | {len(decision.audio_check_items)} |",
        f"| Recommendations | {len(decision.recommendations)} |",
        "",
    ]

    _safe_write(folder / OUT_GATE, '\n'.join(lines))


# ── audio_review_queue.md ─────────────────────────────────────────────────────

def write_audio_queue(folder: Path, candidates: list[NameCandidate],
                      terminology_errors: list | None = None) -> None:
    lines: list[str] = [
        f"# Audio Review Queue",
        f"",
        f"*Generated by ESTRS v{VERSION} — {_ts()}*",
        f"",
        f"Human review required for the following items.",
        f"Listen to the corresponding audio segment and update name_resolution.md.",
        f"",
    ]

    uncertain = [c for c in candidates if c.confidence in ('HIGH', 'MEDIUM')]
    if not uncertain and not terminology_errors:
        lines.append("*Queue is empty — no items require audio review.*\n")
        _safe_write(folder / OUT_AUDIO_QUEUE, '\n'.join(lines))
        return

    if uncertain:
        lines += [
            f"## Uncertain Names ({len(uncertain)} items)",
            "",
        ]
        for i, c in enumerate(uncertain, start=1):
            lines.append(f"### {i}. {c.text}")
            lines.append("")
            lines.append(f"- **Confidence:** {c.confidence}")
            lines.append(f"- **Sources:** {', '.join(c.sources)}")
            lines.append("")
            lines.append("**Context (listen to these segments):**")
            lines.append("")
            for ctx in c.contexts[:2]:
                lines.append(f"> {ctx}")
                lines.append("")
            lines.append("**Resolution:** [ ] Confirmed correct  [ ] Corrected to: ___________")
            lines.append("")

    if terminology_errors:
        lines += [
            f"## Transcription Errors ({len(terminology_errors)} items)",
            "",
        ]
        for e in terminology_errors:
            lines.append(f"- **Found:** `{e.pattern_found}`")
            lines.append(f"  - Suggested: `{e.suggested_correction}`")
            lines.append(f"  - Reason: {e.reason}")
            for src, ln, ctx in e.occurrences[:2]:
                lines.append(f"  - Context ({src}, line {ln}): {ctx}")
            lines.append("")

    _safe_write(folder / OUT_AUDIO_QUEUE, '\n'.join(lines))


# ── automation_log.md ─────────────────────────────────────────────────────────

def append_log(folder: Path, sermon_id: str, status: str,
               files_found: dict[str, str | None],
               notes: str = '') -> None:
    log_path = folder / OUT_LOG
    existing = ''
    if log_path.exists():
        try:
            existing = log_path.read_text(encoding='utf-8')
        except OSError:
            pass

    if not existing:
        existing = f"# ESTRS Automation Log\n\n*Managed by ESTRS v{VERSION}*\n\n---\n\n"

    entry = textwrap.dedent(f"""\
        ## {_ts()} — {sermon_id}

        - **Status:** {status}
        - **AssemblyAI file:** `{files_found.get('assemblyai') or 'not found'}`
        - **MacWhisper file:** `{files_found.get('macwhisper') or 'not found'}`
        {"- **Notes:** " + notes if notes else ""}

        ---

    """)

    _safe_write(log_path, existing + entry)
