#!/bin/bash
# OpenClaw@URANTiOS-ingest install script.
# Idempotent. No curl|sh. Discovers UID/GID from invoking user.
# Run on URANTiOS (204.168.143.98) as the user that owns the repo clone.
#
# UrantiOS governed — Truth, Beauty, Goodness.
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODULE_DIR="$REPO_DIR/openclaw_ingest"
DATA_DIR="/opt/openclaw-data"
COGNEE_DATA_DIR="$HOME/.cognee/data"

echo ""
echo "================================================="
echo "  OpenClaw@URANTiOS-ingest — scaffold install"
echo "================================================="
echo ""

# ── 1. Preconditions ───────────────────────────────────────────────────
info "[1/6] Checking preconditions..."
[ -d "$MODULE_DIR" ] || fail "module not found: $MODULE_DIR (run from repo)"
command -v docker >/dev/null || fail "docker not on PATH"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not available"
if [ "$(id -u)" -eq 0 ]; then
  fail "refuse to run as root. Run as the user that owns the repo clone."
fi
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') · compose plugin OK"

# ── 2. UID/GID discovery ───────────────────────────────────────────────
HOST_UID=$(id -u)
HOST_GID=$(id -g)
info "[2/6] Using UID/GID: $HOST_UID:$HOST_GID (user=$(id -un))"

# ── 3. Host directories ────────────────────────────────────────────────
info "[3/6] Creating host directories..."
sudo mkdir -p "$DATA_DIR"/{ingest/chatcode,ingested/chatcode,classified,canon,logs,evidence}
sudo chown -R "$HOST_UID:$HOST_GID" "$DATA_DIR"
mkdir -p "$COGNEE_DATA_DIR"
ok "data at $DATA_DIR · cognee datastore at $COGNEE_DATA_DIR"

# ── 4. .env ────────────────────────────────────────────────────────────
ENV_FILE="$MODULE_DIR/.env"
info "[4/6] Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Generated by setup/openclaw_ingest_install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
HOST_UID=$HOST_UID
HOST_GID=$HOST_GID
DATASET_NAME=${DATASET_NAME:-mircea_corpus}
LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF
ok ".env generated"

# ── 5. Repo freshness (best-effort; never forces) ──────────────────────
info "[5/6] Repo freshness check..."
if git -C "$REPO_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  if git -C "$REPO_DIR" remote get-url origin >/dev/null 2>&1; then
    git -C "$REPO_DIR" fetch origin --quiet || warn "git fetch failed; continuing with local state"
    CUR_SHA=$(git -C "$REPO_DIR" rev-parse HEAD)
    ok "repo at $CUR_SHA"
  else
    warn "no 'origin' remote; using local state"
  fi
else
  warn "not a git repo; using local state"
fi

# ── 6. Build + launch ──────────────────────────────────────────────────
info "[6/6] Building image + starting container..."
cd "$MODULE_DIR"
docker compose down --remove-orphans >/dev/null 2>&1 || true
docker compose up --build -d

# Wait up to ~30s for healthy (not a hard gate — just a convenience)
for i in $(seq 1 15); do
  sleep 2
  if curl -fsS http://127.0.0.1:8080/health >/dev/null 2>&1; then
    ok "health endpoint responding"
    break
  fi
  if [ "$i" -eq 15 ]; then
    warn "health endpoint not responding yet; container may still be starting"
  fi
done

echo ""
echo "================================================="
echo "  Install complete"
echo "================================================="
echo ""
echo "  Verify:"
echo "    docker logs openclaw-ingest --tail 30"
echo "    curl -s http://127.0.0.1:8080/health | python3 -m json.tool"
echo "    ls -l $DATA_DIR/evidence/"
echo ""
echo "  Invoke a handler:"
echo "    curl -sX POST http://127.0.0.1:8080/tasks \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"handler\": \"smoke_test\", \"payload\": {}}' | python3 -m json.tool"
echo ""
echo "  UrantiOS governed — Truth, Beauty, Goodness"
echo ""
