#!/bin/bash
# Paperclip install script.
# Idempotent. No curl|sh. Discovers UID/GID from invoking user.
# Run on the target host as the user that owns the repo clone.
#
# Requires ScribeClaw and/or OpenClaw already installed so their data
# directories exist (Paperclip mounts them read-only for evidence sweeps).
# Paperclip will still start if those dirs are absent; it will sweep what
# it can find.
#
# UrantiOS governed — Truth, Beauty, Goodness.
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODULE_DIR="$REPO_DIR/paperclip"
DATA_DIR="/opt/paperclip-data"
SCRIBECLAW_EVIDENCE="/opt/scribeclaw-data/evidence"
OPENCLAW_EVIDENCE="/opt/openclaw-data/evidence"

echo ""
echo "================================================="
echo "  Paperclip — evidence bundler install"
echo "================================================="
echo ""

# ── 1. Preconditions ───────────────────────────────────────────────────
info "[1/6] Checking preconditions..."
[ -d "$MODULE_DIR" ] || fail "module not found: $MODULE_DIR (run from repo)"
command -v docker >/dev/null || fail "docker not on PATH"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not available"
if [ "$(id -u)" -eq 0 ]; then
  fail "refuse to run as root. Run as the user that owns the repo clone."
fi
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') · compose plugin OK"

# ── 2. UID/GID discovery ───────────────────────────────────────────────
HOST_UID=$(id -u)
HOST_GID=$(id -g)
info "[2/6] Using UID/GID: $HOST_UID:$HOST_GID (user=$(id -un))"

# ── 3. Host directories ────────────────────────────────────────────────
info "[3/6] Creating host directories..."
sudo mkdir -p "$DATA_DIR"/{bundles,evidence/paperclip,logs}
sudo chown -R "$HOST_UID:$HOST_GID" "$DATA_DIR"
ok "data at $DATA_DIR"

# Check peer evidence directories (non-fatal warnings — Paperclip sweeps
# what it finds; absent peer dirs are skipped silently at runtime).
if [ -d "$SCRIBECLAW_EVIDENCE" ]; then
  ok "scribeclaw evidence: $SCRIBECLAW_EVIDENCE ($(ls "$SCRIBECLAW_EVIDENCE"/*.json 2>/dev/null | wc -l) records)"
else
  warn "scribeclaw evidence not found: $SCRIBECLAW_EVIDENCE"
  warn "  install ScribeClaw first, or create the dir: sudo mkdir -p $SCRIBECLAW_EVIDENCE"
  sudo mkdir -p "$SCRIBECLAW_EVIDENCE"
  sudo chown "$HOST_UID:$HOST_GID" "$SCRIBECLAW_EVIDENCE"
fi

if [ -d "$OPENCLAW_EVIDENCE" ]; then
  ok "openclaw evidence:   $OPENCLAW_EVIDENCE ($(ls "$OPENCLAW_EVIDENCE"/*.json 2>/dev/null | wc -l) records)"
else
  warn "openclaw evidence not found: $OPENCLAW_EVIDENCE"
  warn "  install OpenClaw first, or create the dir: sudo mkdir -p $OPENCLAW_EVIDENCE"
  sudo mkdir -p "$OPENCLAW_EVIDENCE"
  sudo chown "$HOST_UID:$HOST_GID" "$OPENCLAW_EVIDENCE"
fi

# ── 4. .env ────────────────────────────────────────────────────────────
ENV_FILE="$MODULE_DIR/.env"
info "[4/6] Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# Generated by setup/paperclip_install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
HOST_UID=$HOST_UID
HOST_GID=$HOST_GID
LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF
chmod 600 "$ENV_FILE"
ok ".env generated (mode 600)"

# ── 5. Repo freshness (best-effort; never forces) ──────────────────────
info "[5/6] Repo freshness check..."
if git -C "$REPO_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  if git -C "$REPO_DIR" remote get-url origin >/dev/null 2>&1; then
    git -C "$REPO_DIR" fetch origin --quiet || warn "git fetch failed; continuing with local state"
    CUR_SHA=$(git -C "$REPO_DIR" rev-parse HEAD)
    ok "repo at $CUR_SHA"
  else
    warn "no 'origin' remote; using local state"
  fi
else
  warn "not a git repo; using local state"
fi

# ── 6. Build + launch ──────────────────────────────────────────────────
info "[6/6] Building image + starting container..."
cd "$MODULE_DIR"
docker compose down --remove-orphans >/dev/null 2>&1 || true
docker compose up --build -d

for i in $(seq 1 15); do
  sleep 2
  if curl -fsS http://127.0.0.1:8083/health >/dev/null 2>&1; then
    ok "health endpoint responding"
    break
  fi
  if [ "$i" -eq 15 ]; then
    warn "health endpoint not responding yet; container may still be starting"
  fi
done

echo ""
echo "================================================="
echo "  Install complete"
echo "================================================="
echo ""
echo "  Verify:"
echo "    docker logs paperclip --tail 30"
echo "    curl -s http://127.0.0.1:8083/health | python3 -m json.tool"
echo ""
echo "  Bundle all evidence right now:"
echo "    curl -sX POST http://127.0.0.1:8083/tasks \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"handler\": \"bundle_evidence\", \"payload\": {}}' | python3 -m json.tool"
echo ""
echo "  List existing bundles:"
echo "    curl -sX POST http://127.0.0.1:8083/tasks \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"handler\": \"list_bundles\", \"payload\": {}}' | python3 -m json.tool"
echo ""
echo "  Evidence dirs swept:"
echo "    ScribeClaw: $SCRIBECLAW_EVIDENCE"
echo "    OpenClaw:   $OPENCLAW_EVIDENCE"
echo "    Bundles at: $DATA_DIR/bundles/"
echo ""
echo "  UrantiOS governed — Truth, Beauty, Goodness"
echo ""
