#!/bin/bash
# ScribeClaw install script.
# Idempotent. No curl|sh. Discovers UID/GID from invoking user.
# Run on the target host as the user that owns the repo clone.
#
# UrantiOS governed — Truth, Beauty, Goodness.
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODULE_DIR="$REPO_DIR/scribeclaw"
DATA_DIR="/opt/scribeclaw-data"

echo ""
echo "================================================="
echo "  ScribeClaw — scaffold install"
echo "================================================="
echo ""

# ── 1. Preconditions ───────────────────────────────────────────────────
info "[1/5] Checking preconditions..."
[ -d "$MODULE_DIR" ] || fail "module not found: $MODULE_DIR (run from repo)"
command -v docker >/dev/null || fail "docker not on PATH"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not available"
if [ "$(id -u)" -eq 0 ]; then
  fail "refuse to run as root. Run as the user that owns the repo clone."
fi
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') · compose plugin OK"

# ── 2. UID/GID discovery ───────────────────────────────────────────────
HOST_UID=$(id -u)
HOST_GID=$(id -g)
info "[2/5] Using UID/GID: $HOST_UID:$HOST_GID (user=$(id -un))"

# ── 3. Host directories ────────────────────────────────────────────────
info "[3/5] Creating host directories..."
sudo mkdir -p "$DATA_DIR"/{media/in,media/edited,media/audio,transcripts,youtube,models,logs,evidence}
sudo chown -R "$HOST_UID:$HOST_GID" "$DATA_DIR"
ok "data at $DATA_DIR"

# ── 4. .env ────────────────────────────────────────────────────────────
ENV_FILE="$MODULE_DIR/.env"
info "[4/5] Writing $ENV_FILE..."
# Preserve an existing ASSEMBLYAI_API_KEY if the operator already set one.
EXISTING_AAI_KEY=""
if [ -f "$ENV_FILE" ]; then
  EXISTING_AAI_KEY=$(grep -E '^ASSEMBLYAI_API_KEY=' "$ENV_FILE" | cut -d= -f2- || true)
fi
cat > "$ENV_FILE" <<EOF
# Generated by setup/scribeclaw_install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
HOST_UID=$HOST_UID
HOST_GID=$HOST_GID
LOG_LEVEL=${LOG_LEVEL:-INFO}
WHISPER_MODEL=${WHISPER_MODEL:-large-v3}
WHISPER_DEVICE=${WHISPER_DEVICE:-cpu}
WHISPER_COMPUTE=${WHISPER_COMPUTE:-int8}
# Set ASSEMBLYAI_API_KEY to enable transcribe_assemblyai /
# import_assemblyai_transcript. Leave blank to use only the local
# faster-whisper handler (transcribe_ro).
ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY:-$EXISTING_AAI_KEY}
EOF
chmod 600 "$ENV_FILE"
ok ".env generated (mode 600)"

# ── 5. Build + launch ──────────────────────────────────────────────────
info "[5/5] Building image + starting container..."
cd "$MODULE_DIR"
docker compose down --remove-orphans >/dev/null 2>&1 || true
docker compose up --build -d

for i in $(seq 1 20); do
  sleep 2
  if curl -fsS http://127.0.0.1:8081/health >/dev/null 2>&1; then
    ok "health endpoint responding"
    break
  fi
  if [ "$i" -eq 20 ]; then
    warn "health endpoint not responding yet; container may still be starting"
  fi
done

echo ""
echo "================================================="
echo "  Install complete"
echo "================================================="
echo ""
echo "  Verify:"
echo "    docker logs scribeclaw --tail 30"
echo "    curl -s http://127.0.0.1:8081/health | python3 -m json.tool"
echo ""
echo "  Drop a video:"
echo "    cp /path/to/video.mp4 $DATA_DIR/media/in/"
echo ""
echo "  Run full pipeline on that file:"
echo "    curl -sX POST http://127.0.0.1:8081/tasks \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"handler\": \"media_edit\", \"payload\": {\"input\": \"video.mp4\", \"loudnorm\": true}}'"
echo ""
echo "  UrantiOS governed — Truth, Beauty, Goodness"
echo ""
