#!/bin/bash
# SeedanceClaw install script.
# Idempotent. No curl|sh. Discovers UID/GID from invoking user.
# Run on the target host as the user that owns the repo clone.
#
# UrantiOS governed — Truth, Beauty, Goodness.
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODULE_DIR="$REPO_DIR/seedanceclaw"
DATA_DIR="/opt/seedanceclaw-data"

echo ""
echo "================================================="
echo "  SeedanceClaw — scaffold install"
echo "================================================="
echo ""

# ── 1. Preconditions ───────────────────────────────────────────────────
info "[1/5] Checking preconditions..."
[ -d "$MODULE_DIR" ] || fail "module not found: $MODULE_DIR (run from repo)"
command -v docker >/dev/null || fail "docker not on PATH"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin not available"
if [ "$(id -u)" -eq 0 ]; then
  fail "refuse to run as root. Run as the user that owns the repo clone."
fi
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') · compose plugin OK"

# ── 2. UID/GID discovery ───────────────────────────────────────────────
HOST_UID=$(id -u)
HOST_GID=$(id -g)
info "[2/5] Using UID/GID: $HOST_UID:$HOST_GID (user=$(id -un))"

# ── 3. Host directories ────────────────────────────────────────────────
info "[3/5] Creating host directories..."
sudo mkdir -p "$DATA_DIR"/{videos,images,logs,evidence}
sudo chown -R "$HOST_UID:$HOST_GID" "$DATA_DIR"
ok "data at $DATA_DIR"

# ── 4. .env ────────────────────────────────────────────────────────────
ENV_FILE="$MODULE_DIR/.env"
info "[4/5] Writing $ENV_FILE..."

# Preserve an existing FAL_KEY if the operator already set one.
EXISTING_FAL_KEY=""
if [ -f "$ENV_FILE" ]; then
  EXISTING_FAL_KEY=$(grep -E '^FAL_KEY=' "$ENV_FILE" | cut -d= -f2- || true)
fi

# Prompt for FAL_KEY only when it isn't already provided.
if [ -z "${FAL_KEY:-}" ] && [ -z "$EXISTING_FAL_KEY" ]; then
  echo ""
  warn "FAL_KEY is not set. Obtain a key at https://fal.ai"
  read -rsp "  Enter your FAL_KEY (input hidden, press Enter to skip): " INPUT_FAL_KEY
  echo ""
  FAL_KEY="${INPUT_FAL_KEY:-}"
else
  FAL_KEY="${FAL_KEY:-$EXISTING_FAL_KEY}"
fi

cat > "$ENV_FILE" <<EOF
# Generated by setup/seedanceclaw_install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
HOST_UID=$HOST_UID
HOST_GID=$HOST_GID
LOG_LEVEL=${LOG_LEVEL:-INFO}
# fal.ai API key — required for text_to_video and image_to_video handlers.
# Get yours at https://fal.ai (dashboard → API Keys).
FAL_KEY=${FAL_KEY}
# Seedance model IDs — change to switch between v1 Pro / v2 etc.
SEEDANCE_MODEL_T2V=${SEEDANCE_MODEL_T2V:-fal-ai/bytedance/seedance/v1/pro/text-to-video}
SEEDANCE_MODEL_I2V=${SEEDANCE_MODEL_I2V:-fal-ai/bytedance/seedance/v1/pro/image-to-video}
EOF
chmod 600 "$ENV_FILE"
ok ".env generated (mode 600)"

if [ -z "$FAL_KEY" ]; then
  warn "FAL_KEY is empty — generation handlers will refuse at runtime."
  warn "Set FAL_KEY in $ENV_FILE and restart the container."
fi

# ── 5. Build + launch ──────────────────────────────────────────────────
info "[5/5] Building image + starting container..."
cd "$MODULE_DIR"
docker compose down --remove-orphans >/dev/null 2>&1 || true
docker compose up --build -d

for i in $(seq 1 20); do
  sleep 2
  if curl -fsS http://127.0.0.1:8086/health >/dev/null 2>&1; then
    ok "health endpoint responding"
    break
  fi
  if [ "$i" -eq 20 ]; then
    warn "health endpoint not responding yet; container may still be starting"
  fi
done

echo ""
echo "================================================="
echo "  Install complete"
echo "================================================="
echo ""
echo "  Verify:"
echo "    docker logs seedanceclaw --tail 30"
echo "    curl -s http://127.0.0.1:8086/health | python3 -m json.tool"
echo ""
echo "  Generate a video:"
echo "    curl -sX POST http://127.0.0.1:8086/tasks \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"handler\": \"text_to_video\", \"payload\": {\"prompt\": \"A sunrise over mountains, cinematic\"}}'"
echo ""
echo "  Videos saved to: $DATA_DIR/videos/"
echo ""
echo "  UrantiOS governed — Truth, Beauty, Goodness"
echo ""
